version: "3.7"
volumes:
  databasevol:
services:

  database:
    container_name: mysql
    image: mysql:latest
    restart: always
    volumes:
      - ./src/main/resources/database:/docker-entrypoint-initdb.d/
      - ./terminplanerdb/mysql/data:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"


  terminplaner:
    container_name: terminplaner
    command: [ "/app/wait-for-it.sh", "mysql:3306", "--timeout=0", "--", "java",  "-jar", "/app/app.jar" ]
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "CLIENT_ID=${CLIENT_ID}"
      - "CLIENT_SECRET=${CLIENT_SECRET}"
      - "APP_ID=${APP_ID}"
      - "INSTALLATION_ID=${INSTALLATION_ID}"
      - "ORGANISATION_NAME=${ORGANISATION_NAME}"




